name: "cardio-bot-app"

services:
  cardio-db:
    image: 'postgres:latest'
    tty: true
    env_file: ./.env
    container_name: 'cardio-db'
    environment:
      - 'POSTGRES_DB=cardio-db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - 'cardio-db-volume:/var/lib/postgresql/data'

  cardio-bot:
    image: 'cardio-bot:latest'
    container_name: 'cardio-bot'
    env_file: ./.env
    tty: true
    depends_on:
      - cardio-db

volumes:
  cardio-db-volume: