name: "cardio-bot-app"

services:
  cardio-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cardio-db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - 'cardio-db-volume:/var/lib/postgresql/data'

  cardio-bot:
    image: 'cardio-bot:latest'
    env_file: .env
    tty: true
    depends_on:
      - cardio-db

volumes:
  cardio-db-volume: