spring:
  application:
    name: "cardioTelegramBot"
  datasource:
    url: "jdbc:postgresql://cardio-db:5432/cardio-db"
    driver-class-name: "org.postgresql.Driver"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
  data:
    table: "winners.csv"

telegram:
  is-dev-mode: "false"
  guide:
    file: "${GUIDE}"
  bot:
    main-token: "${MAIN_TOKEN}"
    logger-token: "${LOGGER_TOKEN}"
    dev-token: "${DEV_TOKEN}"
  logger:
    dev-chat-id: "1233629516"
    id: "-1002118949277"
    info: "62"
    warn: "64"
    error: "66"
  creator:
    username: "@baymukanov"
  channel:
    id: "-1001894647431"
    username: "abaymukanov"
  makeAppointment:
    link: "https://baymukanov.ru/#contacts"
  joinPrivateChat:
    link: "https://baymukanov.ru/club"
  reviews:
    link: "https://prodoctorov.ru/moskva/vrach/457300-baymukanov/#rating"
  education:
    link: "https://baymukanov.ru/#education"