spring:
  application:
    name: "cardioTelegramBot"
  file:
    location: "src/main/resources"
  datasource:
    url: "jdbc:postgresql://cardio-db:5432/cardio-db"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
  data:
    table: "winners.csv"
    referral: "referral.txt"

telegram:
  logger:
    id: "-1002118949277"
    info: "62"
    warn: "64"
    error: "66"
  creator:
    username: "@baymukanov"
  channel:
    id: "-1001894647431"
    username: "abaymukanov"
  assessRisks:
    link: "https://baymukanov.ru/survey"
  makeAppointment:
    link: "https://baymukanov.ru/"
  reviews:
    link: "https://prodoctorov.ru/moskva/vrach/457300-baymukanov/#rating"
  education:
    link: "https://baymukanov.ru/#education"